#!/usr/bin/env python3
"""
Quick Email Setup for MatchGen
This script creates a .env file with email configuration.
"""

import os
from pathlib import Path

def create_env_file():
    """Create a .env file with email configuration."""
    
    print("🚀 MatchGen Quick Email Setup")
    print("=" * 40)
    
    # Get email configuration from user
    print("\n📧 Email Configuration")
    print("We'll set up Gmail (recommended) or you can use another provider")
    
    email_provider = input("\nChoose email provider (gmail/outlook/yahoo/custom): ").lower().strip()
    
    if email_provider == "gmail":
        email_host = "smtp.gmail.com"
        email_port = "587"
        email_use_tls = "True"
    elif email_provider == "outlook":
        email_host = "smtp-mail.outlook.com"
        email_port = "587"
        email_use_tls = "True"
    elif email_provider == "yahoo":
        email_host = "smtp.mail.yahoo.com"
        email_port = "587"
        email_use_tls = "True"
    else:
        email_host = input("Enter SMTP host: ").strip()
        email_port = input("Enter SMTP port (usually 587): ").strip() or "587"
        email_use_tls = input("Use TLS? (True/False): ").strip() or "True"
    
    email_user = input("Enter your email address: ").strip()
    email_password = input("Enter your email password/app password: ").strip()
    
    # Get frontend URL
    frontend_url = input("Enter your frontend URL (e.g., http://localhost:3000): ").strip()
    if not frontend_url:
        frontend_url = "http://localhost:3000"
    
    # Create .env content
    env_content = f"""# MatchGen Backend Environment Configuration
# Generated by quick_email_setup.py

# Database Configuration
DATABASE_URL=sqlite:///db.sqlite3

# Secret Key (generate a new one for production)
SECRET_KEY=your-secret-key-here-change-this-in-production

# Debug Mode
DEBUG=True

# Allowed Hosts
ALLOWED_HOSTS=localhost,127.0.0.1

# Frontend URL
FRONTEND_URL={frontend_url}

# Email Configuration
EMAIL_HOST={email_host}
EMAIL_PORT={email_port}
EMAIL_USE_TLS={email_use_tls}
EMAIL_HOST_USER={email_user}
EMAIL_HOST_PASSWORD={email_password}
DEFAULT_FROM_EMAIL={email_user}

# CORS Settings
CORS_ALLOWED_ORIGINS={frontend_url}
"""
    
    # Write .env file
    env_path = Path("matchgen-backend") / ".env"
    
    try:
        with open(env_path, 'w') as f:
            f.write(env_content)
        
        print(f"\n✅ .env file created successfully at {env_path}")
        print("\n📋 Next Steps:")
        print("1. Restart your Django server")
        print("2. Run: python setup_email.py")
        print("3. Test email sending")
        
        if email_provider == "gmail":
            print("\n💡 Gmail Setup Reminder:")
            print("- Enable 2-Factor Authentication")
            print("- Generate an App Password")
            print("- Use the App Password (not your regular password)")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        print(f"Please create the file manually at {env_path}")

if __name__ == "__main__":
    create_env_file()



