# Generated by Django 5.1.7 on 2025-08-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_club_selected_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
