# Generated by Django 5.1.7 on 2025-09-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_subscription_canceled_stripe_id'),
        ('users', '0013_add_subscription_fields'),
        ('users', '0014_add_subscription_fields_final'),
    ]

    operations = [
    ]
