# Generated by Django 5.1.7 on 2025-09-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_add_scheduled_tier'),
        ('users', '0015_merge_20250922_1618'),
    ]

    operations = [
    ]
