# Generated by Django 5.1.7 on 2025-04-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_match_club_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="matchday_post_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
