# Generated by Django 5.1.7 on 2025-08-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_match_matchday_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='club_logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchday_post_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='opponent_logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='sponsor',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='formatted_pic',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_pic',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='sponsor',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
