# Generated by Django 5.1.7 on 2025-08-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_extend_urlfield_max_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='home_away',
            field=models.CharField(choices=[('HOME', 'Home'), ('AWAY', 'Away')], default='HOME', max_length=4),
        ),
    ]
