# Generated by Django 5.1.7 on 2025-10-19 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_match_home_away'),
        ('users', '0016_merge_20250923_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='match',
            name='fixture_key',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='match',
            name='kickoff_local_tz',
            field=models.CharField(default='Europe/London', max_length=64),
        ),
        migrations.AddField(
            model_name='match',
            name='kickoff_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='last_synced_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='match',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='round_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='match',
            name='score_away',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score_home',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='source',
            field=models.CharField(choices=[('fulltime_html', 'FA Full-Time (HTML via proxy)'), ('upload', 'CSV/XLSX Upload'), ('manual', 'Manual'), ('ai_import', 'AI Import'), ('other', 'Other')], default='manual', max_length=32),
        ),
        migrations.AddField(
            model_name='match',
            name='source_competition_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='source_team_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default='SCHEDULED', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('club', 'fixture_key')},
        ),
        migrations.CreateModel(
            name='FullTimeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_url', models.URLField()),
                ('team_display_name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulltime_sources', to='users.club')),
            ],
        ),
    ]
