# Generated by Django 5.1.7 on 2025-11-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_match_away_team_match_competition_match_fixture_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='starting_xi_post_url',
            field=models.URLField(blank=True, help_text='URL for uploaded starting XI post', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='upcoming_fixture_post_url',
            field=models.URLField(blank=True, help_text='URL for uploaded upcoming fixture post', max_length=500, null=True),
        ),
    ]
