# Generated by Django 5.1.7 on 2025-11-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_add_upcoming_fixture_and_starting_xi_post_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cutout_url',
            field=models.URLField(blank=True, help_text='URL for uploaded player cutout image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='highlight_away_url',
            field=models.URLField(blank=True, help_text='URL for uploaded highlight image (Away)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='highlight_home_url',
            field=models.URLField(blank=True, help_text='URL for uploaded highlight image (Home)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='potm_url',
            field=models.URLField(blank=True, help_text='URL for uploaded Player of the Match image', max_length=500, null=True),
        ),
    ]
