# Generated by Django 5.1.7 on 2025-11-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_add_player_bespoke_graphics'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='fulltime_post_url',
            field=models.URLField(blank=True, help_text='URL for uploaded fulltime post', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='halftime_post_url',
            field=models.URLField(blank=True, help_text='URL for uploaded halftime post', max_length=500, null=True),
        ),
    ]
