# Generated by Django 5.1.7 on 2025-10-05 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="User's name", max_length=255)),
                ('email', models.EmailField(help_text="User's email address", max_length=254)),
                ('feedback_type', models.CharField(choices=[('general', 'General Feedback'), ('bug', 'Bug Report'), ('feature', 'Feature Request'), ('support', 'Technical Support'), ('billing', 'Billing Question')], default='general', help_text='Type of feedback', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Brief subject line', max_length=255, null=True)),
                ('message', models.TextField(help_text='Detailed feedback message')),
                ('rating', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=5, help_text="User's rating of the service")),
                ('allow_contact', models.BooleanField(default=True, help_text='Whether user allows follow-up contact')),
                ('subscribe_newsletter', models.BooleanField(default=False, help_text='Whether user wants to subscribe to newsletter')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', help_text='Current status of the feedback', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the feedback', max_length=10)),
                ('admin_response', models.TextField(blank=True, help_text='Response from admin team', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin team', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feedback_type'], name='feedback_fe_feedbac_ba1d78_idx'), models.Index(fields=['status'], name='feedback_fe_status_35d074_idx'), models.Index(fields=['priority'], name='feedback_fe_priorit_fbe607_idx'), models.Index(fields=['created_at'], name='feedback_fe_created_84c297_idx')],
            },
        ),
    ]
