# Generated by Django 5.1.7 on 2025-04-14 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphicpack',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='graphicpack',
            name='zip_file',
        ),
        migrations.AddField(
            model_name='graphicpack',
            name='preview_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graphicpack',
            name='zip_file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('matchday', 'Matchday'), ('result', 'Result'), ('lineup', 'Lineup'), ('fixture', 'Fixture'), ('upcomingFixtures', 'Upcoming Fixtures'), ('lineup', 'Lineup'), ('alert', 'Alert'), ('player', 'Player')], max_length=100)),
                ('image_url', models.URLField()),
                ('sport', models.CharField(blank=True, max_length=50)),
                ('graphic_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='graphicpack.graphicpack')),
            ],
        ),
    ]
