# Generated by Django 5.1.7 on 2025-04-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphicpack", "0004_textelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="textelement",
            name="quinary_position_x",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="textelement",
            name="quinary_position_y",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="textelement",
            name="senary_position_x",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="textelement",
            name="senary_position_y",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="textelement",
            name="septenary_position_x",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="textelement",
            name="septenary_position_y",
            field=models.FloatField(default=0),
        ),
    ]
