# Generated by Django 5.1.7 on 2025-04-24 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphicpack", "0005_textelement_quinary_position_x_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_key", models.CharField(max_length=50)),
                ("maintain_aspect_ratio", models.BooleanField(default=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_elements",
                        to="graphicpack.template",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StringElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_key", models.CharField(max_length=50)),
                ("font_family", models.CharField(default="Arial.ttf", max_length=100)),
                ("font_size", models.IntegerField(default=24)),
                ("color", models.CharField(default="#FFFFFF", max_length=7)),
                (
                    "alignment",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="left",
                        max_length=10,
                    ),
                ),
                ("max_width", models.FloatField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="string_elements",
                        to="graphicpack.template",
                    ),
                ),
            ],
        ),
    ]
