# Generated by Django 5.1.7 on 2025-08-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0009_templateelement_content_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphicpack',
            name='preview_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='graphicpack',
            name='zip_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
