# Generated by Django 5.1.7 on 2025-08-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0010_extend_urlfield_max_lengths'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templateelement',
            options={'ordering': ['z_index', 'id']},
        ),
        migrations.AddField(
            model_name='stringelement',
            name='font_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('italic', 'Italic')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='stringelement',
            name='font_weight',
            field=models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('light', 'Light')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='stringelement',
            name='letter_spacing',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stringelement',
            name='line_height',
            field=models.FloatField(default=1.2),
        ),
        migrations.AddField(
            model_name='stringelement',
            name='shadow_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='stringelement',
            name='shadow_offset_x',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='stringelement',
            name='shadow_offset_y',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='stringelement',
            name='text_shadow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templateelement',
            name='max_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templateelement',
            name='use_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templateelement',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='templateelement',
            name='z_index',
            field=models.IntegerField(default=0),
        ),
    ]
