# Generated by Django 5.1.7 on 2025-08-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0011_alter_templateelement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='content_type',
            field=models.CharField(choices=[('matchday', 'Matchday'), ('result', 'Result'), ('lineup', 'Lineup'), ('fixture', 'Fixture'), ('upcomingFixtures', 'Upcoming Fixtures'), ('upcomingFixture', 'Upcoming Fixture'), ('startingXI', 'Starting XI'), ('goal', 'Goal'), ('sub', 'Substitution'), ('halftime', 'Halftime'), ('fulltime', 'Full-time'), ('alert', 'Alert'), ('player', 'Player')], max_length=100),
        ),
    ]
