# Generated by Django 5.1.7 on 2025-08-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0012_alter_template_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stringelement',
            name='template',
        ),
        migrations.RemoveField(
            model_name='templateelement',
            name='template',
        ),
        migrations.RemoveField(
            model_name='textelement',
            name='template',
        ),
        migrations.AddField(
            model_name='template',
            name='template_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='ImageElement',
        ),
        migrations.DeleteModel(
            name='StringElement',
        ),
        migrations.DeleteModel(
            name='TemplateElement',
        ),
        migrations.DeleteModel(
            name='TextElement',
        ),
    ]
