# Generated by Django 5.1.7 on 2025-08-21 16:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0013_remove_stringelement_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(help_text='e.g., matchday, upcoming, startingxi', max_length=50)),
                ('element_name', models.CharField(help_text='e.g., date, time, venue, opponent', max_length=50)),
                ('position_x', models.IntegerField(default=400, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)])),
                ('position_y', models.IntegerField(default=150, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)])),
                ('font_size', models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(100)])),
                ('font_family', models.CharField(default='Arial', max_length=100)),
                ('font_color', models.CharField(default='#FFFFFF', help_text='Hex color code', max_length=7)),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('font_weight', models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graphic_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_elements', to='graphicpack.graphicpack')),
            ],
            options={
                'ordering': ['graphic_pack', 'content_type', 'element_name'],
                'unique_together': {('graphic_pack', 'content_type', 'element_name')},
            },
        ),
    ]
