# Generated by Django 5.1.7 on 2025-08-24 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0014_textelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='textelement',
            name='element_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', help_text='Type of element to render', max_length=10),
        ),
        migrations.AddField(
            model_name='textelement',
            name='image_height',
            field=models.IntegerField(default=100, help_text='Height of image in pixels', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='image_width',
            field=models.IntegerField(default=100, help_text='Width of image in pixels', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='maintain_aspect_ratio',
            field=models.BooleanField(default=True, help_text='Maintain aspect ratio when resizing image'),
        ),
        migrations.AlterField(
            model_name='textelement',
            name='element_name',
            field=models.CharField(help_text='e.g., date, time, venue, opponent, logo', max_length=50),
        ),
    ]
