# Generated by Django 5.1.7 on 2025-08-24 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0015_textelement_element_type_textelement_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textelement',
            name='away_position_x',
            field=models.IntegerField(default=400, help_text='X position for away fixtures', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='away_position_y',
            field=models.IntegerField(default=150, help_text='Y position for away fixtures', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='home_position_x',
            field=models.IntegerField(default=400, help_text='X position for home fixtures', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='home_position_y',
            field=models.IntegerField(default=150, help_text='Y position for home fixtures', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
