# Generated by Django 5.1.7 on 2025-08-24 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0016_textelement_away_position_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textelement',
            name='image_brightness',
            field=models.FloatField(default=1.0, help_text='Brightness multiplier (0.1 to 3.0)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3.0)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='image_color_filter',
            field=models.CharField(choices=[('none', 'No Filter'), ('grayscale', 'Grayscale'), ('sepia', 'Sepia'), ('invert', 'Invert Colors'), ('custom', 'Custom Color')], default='none', help_text='Color filter to apply to image', max_length=20),
        ),
        migrations.AddField(
            model_name='textelement',
            name='image_color_tint',
            field=models.CharField(default='#FFFFFF', help_text='Hex color for tinting (use with custom filter)', max_length=7),
        ),
        migrations.AddField(
            model_name='textelement',
            name='image_contrast',
            field=models.FloatField(default=1.0, help_text='Contrast multiplier (0.1 to 3.0)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3.0)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='image_saturation',
            field=models.FloatField(default=1.0, help_text='Saturation multiplier (0.0 to 3.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)]),
        ),
    ]
