# Generated by Django 5.1.7 on 2025-09-25 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0017_textelement_image_brightness_and_more'),
        ('users', '0016_merge_20250923_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphicpack',
            name='primary_color',
            field=models.CharField(default='#000000', help_text='Primary color for the pack', max_length=7),
        ),
        migrations.AddField(
            model_name='graphicpack',
            name='tier',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('semipro', 'SemiPro'), ('pro', 'Pro')], help_text='Subscription tier required', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='graphicpack',
            name='assigned_club',
            field=models.ForeignKey(blank=True, help_text='Specific club (null for all clubs)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.club'),
        ),
        migrations.AddField(
            model_name='graphicpack',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the pack is active'),
        ),
        migrations.AddField(
            model_name='graphicpack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='graphicpack',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='file_url',
            field=models.URLField(blank=True, help_text='URL of the uploaded file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
