# Generated by Django 5.1.7 on 2025-09-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0018_auto_20250925_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphicpack',
            name='category',
            field=models.CharField(blank=True, help_text='Category of the graphic pack', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='graphicpack',
            name='sport',
            field=models.CharField(blank=True, help_text='Sport type for the graphic pack', max_length=50, null=True),
        ),
    ]
