# Generated by Django 5.1.7 on 2025-09-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0019_graphicpack_category_graphicpack_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphicpack',
            name='category',
        ),
    ]
