# Generated by Django 5.1.7 on 2025-09-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0020_remove_graphicpack_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='textelement',
            name='text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', help_text='How text is aligned within the element bounds', max_length=10),
        ),
    ]
