# Generated by Django 5.1.7 on 2025-09-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0021_textelement_text_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='textelement',
            name='anchor_point',
            field=models.CharField(choices=[('lt', 'Left-Top'), ('rt', 'Right-Top'), ('mt', 'Middle-Top'), ('lm', 'Left-Middle'), ('rm', 'Right-Middle'), ('mm', 'Middle-Middle'), ('lb', 'Left-Bottom'), ('rb', 'Right-Bottom'), ('mb', 'Middle-Bottom')], default='mt', help_text='Anchor point for positioning the element', max_length=10),
        ),
    ]
