# Generated by Django 5.1.7 on 2025-09-30 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0022_textelement_anchor_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='textelement',
            name='top_left_x',
            field=models.IntegerField(default=0, help_text='Top-left X position from PSD layer', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='top_left_y',
            field=models.IntegerField(default=0, help_text='Top-left Y position from PSD layer', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
