# Generated by Django 5.1.7 on 2025-09-30 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0023_textelement_top_left_x_textelement_top_left_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='textelement',
            name='top_right_x',
            field=models.IntegerField(default=0, help_text='Top-right X position from PSD layer', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='top_right_y',
            field=models.IntegerField(default=0, help_text='Top-right Y position from PSD layer', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
