# Generated by Django 5.1.7 on 2025-09-30 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0024_textelement_top_right_x_textelement_top_right_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='textelement',
            name='left_x',
            field=models.IntegerField(default=0, help_text='Left X position from PSD layer', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='left_y',
            field=models.IntegerField(default=0, help_text='Left Y position from PSD layer', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='right_x',
            field=models.IntegerField(default=0, help_text='Right X position from PSD layer', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='right_y',
            field=models.IntegerField(default=0, help_text='Right Y position from PSD layer', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
