# Generated by Django 5.1.7 on 2025-09-30 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0025_textelement_left_x_textelement_left_y_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textelement',
            name='anchor_point',
        ),
        migrations.RemoveField(
            model_name='textelement',
            name='left_x',
        ),
        migrations.RemoveField(
            model_name='textelement',
            name='left_y',
        ),
        migrations.RemoveField(
            model_name='textelement',
            name='right_x',
        ),
        migrations.RemoveField(
            model_name='textelement',
            name='right_y',
        ),
        migrations.AddField(
            model_name='textelement',
            name='top_center_x',
            field=models.IntegerField(default=0, help_text='Top-center X position for center alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='top_center_y',
            field=models.IntegerField(default=0, help_text='Top-center Y position for center alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='textelement',
            name='top_left_x',
            field=models.IntegerField(default=0, help_text='Top-left X position for left alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='textelement',
            name='top_left_y',
            field=models.IntegerField(default=0, help_text='Top-left Y position for left alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='textelement',
            name='top_right_x',
            field=models.IntegerField(default=0, help_text='Top-right X position for right alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='textelement',
            name='top_right_y',
            field=models.IntegerField(default=0, help_text='Top-right Y position for right alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
