# Generated by Django 5.1.7 on 2025-10-01 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0026_remove_textelement_anchor_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textelement',
            name='bottom_center_x',
            field=models.IntegerField(default=0, help_text='Bottom-center X position for center alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='bottom_center_y',
            field=models.IntegerField(default=0, help_text='Bottom-center Y position for center alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='bottom_left_x',
            field=models.IntegerField(default=0, help_text='Bottom-left X position for left alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='bottom_left_y',
            field=models.IntegerField(default=0, help_text='Bottom-left Y position for left alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='bottom_right_x',
            field=models.IntegerField(default=0, help_text='Bottom-right X position for right alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='bottom_right_y',
            field=models.IntegerField(default=0, help_text='Bottom-right Y position for right alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='position_anchor',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='top', help_text='Whether to use top or bottom anchor points for positioning', max_length=10),
        ),
    ]
