# Generated by Django 5.1.7 on 2025-10-03 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0027_textelement_bottom_center_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textelement',
            name='center_center_x',
            field=models.IntegerField(default=0, help_text='Center-center X position for center alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='center_center_y',
            field=models.IntegerField(default=0, help_text='Center-center Y position for center alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='center_left_x',
            field=models.IntegerField(default=0, help_text='Center-left X position for left alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='center_left_y',
            field=models.IntegerField(default=0, help_text='Center-left Y position for left alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='center_right_x',
            field=models.IntegerField(default=0, help_text='Center-right X position for right alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='textelement',
            name='center_right_y',
            field=models.IntegerField(default=0, help_text='Center-right Y position for right alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='textelement',
            name='font_size',
            field=models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(8)]),
        ),
    ]
