# Generated by Django 5.1.7 on 2025-10-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0028_textelement_center_center_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textelement',
            name='position_anchor',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='top', help_text='Whether to use top or bottom anchor points for positioning', max_length=10),
        ),
    ]
