# Generated by Django 5.1.7 on 2025-10-05 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0029_alter_textelement_position_anchor'),
        ('users', '0016_merge_20250923_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display name for the media item', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('media_type', models.CharField(choices=[('club_logo', 'Club Logo'), ('opponent_logo', 'Opponent Logo'), ('player_photo', 'Player Photo'), ('template', 'Template'), ('background', 'Background Image'), ('banner', 'Banner Image'), ('other', 'Other')], help_text='Type of media', max_length=50)),
                ('category', models.CharField(choices=[('logos', 'Logos'), ('players', 'Player Photos'), ('templates', 'Templates'), ('backgrounds', 'Backgrounds'), ('banners', 'Banners'), ('other', 'Other')], help_text='Category for organization', max_length=50)),
                ('file_url', models.URLField(help_text='URL of the uploaded file', max_length=500)),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='MIME type (e.g., image/jpeg)', max_length=50)),
                ('width', models.IntegerField(blank=True, help_text='Image width in pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Image height in pixels', null=True)),
                ('cloudinary_public_id', models.CharField(blank=True, help_text='Cloudinary public ID', max_length=255, null=True)),
                ('cloudinary_folder', models.CharField(blank=True, help_text='Cloudinary folder', max_length=255, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for categorization')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this media item is active')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this media has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='users.club')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['club', 'media_type'], name='graphicpack_club_id_ef5915_idx'), models.Index(fields=['club', 'category'], name='graphicpack_club_id_4b63da_idx'), models.Index(fields=['club', 'is_active'], name='graphicpack_club_id_15a916_idx')],
            },
        ),
    ]
