# Generated by Django 5.1.7 on 2025-10-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0030_mediaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphicpack',
            name='is_bespoke',
            field=models.BooleanField(default=False, help_text='Whether this is a bespoke pack (hidden from general templates)'),
        ),
    ]
