# Generated by Django 5.1.7 on 2025-11-26 21:21

from django.db import migrations, models


def set_default_homeoraway(apps, schema_editor):
    """Set all existing templates to 'Default' for homeoraway field."""
    Template = apps.get_model('graphicpack', 'Template')
    Template.objects.all().update(homeoraway='Default')


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0031_graphicpack_is_bespoke'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='homeoraway',
            field=models.CharField(choices=[('Default', 'Default'), ('Home', 'Home'), ('Away', 'Away')], default='Default', help_text='Whether this template is for Home, Away, or Default (both)', max_length=20),
        ),
        migrations.RunPython(set_default_homeoraway, migrations.RunPython.noop),
    ]
