# Generated by Django 5.1.7 on 2025-09-04 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PSDDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='psd_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psd_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PSDLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('x', models.IntegerField(help_text='X coordinate of layer')),
                ('y', models.IntegerField(help_text='Y coordinate of layer')),
                ('width', models.IntegerField(help_text='Width of layer')),
                ('height', models.IntegerField(help_text='Height of layer')),
                ('visible', models.BooleanField(default=True)),
                ('opacity', models.FloatField(default=100.0)),
                ('layer_type', models.CharField(default='layer', max_length=50)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='psd_processor.psddocument')),
            ],
            options={
                'ordering': ['y', 'x'],
            },
        ),
    ]
