# Generated by Django 5.1.7 on 2025-09-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psd_processor', '0002_psdlayer_center_x_psdlayer_center_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psdlayer',
            name='x',
            field=models.IntegerField(help_text='X coordinate of layer (top-left corner)'),
        ),
        migrations.AlterField(
            model_name='psdlayer',
            name='y',
            field=models.IntegerField(help_text='Y coordinate of layer (top-left corner)'),
        ),
    ]
