# Generated by Django 5.1.7 on 2025-09-28 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicpack', '0020_remove_graphicpack_category'),
        ('psd_processor', '0003_alter_psdlayer_x_alter_psdlayer_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='psdlayer',
            name='content_type',
            field=models.CharField(blank=True, help_text='Content type (fulltime, halftime, matchday, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='graphic_pack',
            field=models.ForeignKey(blank=True, help_text='Associated graphic pack', null=True, on_delete=django.db.models.deletion.CASCADE, to='graphicpack.graphicpack'),
        ),
    ]
