# Generated by Django 5.1.7 on 2025-09-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psd_processor', '0004_psdlayer_content_type_psdlayer_graphic_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='psdlayer',
            name='left_x',
            field=models.IntegerField(default=0, help_text='Left X coordinate of layer'),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='left_y',
            field=models.IntegerField(default=0, help_text='Left Y coordinate of layer'),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='right_x',
            field=models.IntegerField(default=0, help_text='Right X coordinate of layer'),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='right_y',
            field=models.IntegerField(default=0, help_text='Right Y coordinate of layer'),
        ),
    ]
