# Generated by Django 5.1.7 on 2025-09-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psd_processor', '0005_psdlayer_left_x_psdlayer_left_y_psdlayer_right_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psdlayer',
            name='top_center_x',
            field=models.IntegerField(default=0, help_text='Top-center X coordinate for text positioning'),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='top_center_y',
            field=models.IntegerField(default=0, help_text='Top-center Y coordinate for text positioning'),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='top_left_x',
            field=models.IntegerField(default=0, help_text='Top-left X coordinate for text positioning'),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='top_left_y',
            field=models.IntegerField(default=0, help_text='Top-left Y coordinate for text positioning'),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='top_right_x',
            field=models.IntegerField(default=0, help_text='Top-right X coordinate for text positioning'),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='top_right_y',
            field=models.IntegerField(default=0, help_text='Top-right Y coordinate for text positioning'),
        ),
    ]
