# Generated by Django 5.1.7 on 2025-10-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psd_processor', '0006_psdlayer_top_center_x_psdlayer_top_center_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psdlayer',
            name='bottom_center_x',
            field=models.IntegerField(default=0, help_text='Bottom-center X coordinate for text positioning'),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='bottom_center_y',
            field=models.IntegerField(default=0, help_text='Bottom-center Y coordinate for text positioning'),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='bottom_left_x',
            field=models.IntegerField(default=0, help_text='Bottom-left X coordinate for text positioning'),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='bottom_left_y',
            field=models.IntegerField(default=0, help_text='Bottom-left Y coordinate for text positioning'),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='bottom_right_x',
            field=models.IntegerField(default=0, help_text='Bottom-right X coordinate for text positioning'),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='bottom_right_y',
            field=models.IntegerField(default=0, help_text='Bottom-right Y coordinate for text positioning'),
        ),
    ]
