# Generated by Django 5.1.7 on 2025-10-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psd_processor', '0007_psdlayer_bottom_center_x_psdlayer_bottom_center_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psdlayer',
            name='center_center_x',
            field=models.IntegerField(default=0, help_text='Center-center X coordinate for text positioning'),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='center_center_y',
            field=models.IntegerField(default=0, help_text='Center-center Y coordinate for text positioning'),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='center_left_x',
            field=models.IntegerField(default=0, help_text='Center-left X coordinate for text positioning'),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='center_left_y',
            field=models.IntegerField(default=0, help_text='Center-left Y coordinate for text positioning'),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='center_right_x',
            field=models.IntegerField(default=0, help_text='Center-right X coordinate for text positioning'),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='center_right_y',
            field=models.IntegerField(default=0, help_text='Center-right Y coordinate for text positioning'),
        ),
    ]
