# Generated by Django 5.1.7 on 2025-10-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psd_processor', '0008_psdlayer_center_center_x_psdlayer_center_center_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psdlayer',
            name='font_color',
            field=models.CharField(blank=True, help_text='Font color in hex format', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='font_family',
            field=models.CharField(blank=True, help_text='Font family name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='font_size',
            field=models.FloatField(blank=True, help_text='Font size in points', null=True),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='font_weight',
            field=models.CharField(blank=True, help_text='Font weight (normal, bold, etc.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='max_width',
            field=models.IntegerField(blank=True, help_text='Maximum width for text wrapping', null=True),
        ),
        migrations.AddField(
            model_name='psdlayer',
            name='text_content',
            field=models.TextField(blank=True, help_text='Original text content of the layer', null=True),
        ),
    ]
