# Generated by Django 5.1.7 on 2025-10-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psd_processor', '0009_psdlayer_font_color_psdlayer_font_family_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psdlayer',
            name='text_content',
        ),
    ]
